from typing import List
from app.places.models import PlaceCategory, PlaceItem, AccessibilityInfo, EVChargingInfo

CATEGORIES_LIST: List[PlaceCategory] = [
    PlaceCategory(id="hospital", label="Hospitals", icon="hospital", group="emergency", description="Emergency care, 24/7 trauma & multispecialty hospitals", popular=True, is_emergency=True),
    PlaceCategory(id="pharmacy", label="Pharmacies / Medicine", icon="pill", group="medical", description="24h chemist, prescription drugs & first-aid essentials", popular=True, is_emergency=True),
    PlaceCategory(id="restaurant", label="Restaurants", icon="utensils", group="sustenance", description="South Indian meals, vegetarian & transit eateries", popular=True),
    PlaceCategory(id="fuel", label="Petrol / Fuel", icon="fuel", group="mobility", description="Petrol bunks, diesel, air & highway fuel pumps", popular=True),
    PlaceCategory(id="toilet", label="Public Toilets", icon="bath", group="civic", description="Clean municipal & transit hub public restrooms", popular=True),
    PlaceCategory(id="atm", label="ATMs", icon="credit-card", group="financial", description="24/7 cash dispensers from major Indian banks", popular=True),
    PlaceCategory(id="bank", label="Banks", icon="landmark", group="financial", description="Commercial banking branches & forex counters"),
    PlaceCategory(id="grocery", label="Grocery Stores", icon="shopping-cart", group="sustenance", description="Daily provisions, packaged snacks & FMCG essentials"),
    PlaceCategory(id="food_water", label="Food / Water", icon="cup-soda", group="sustenance", description="RO purified water kiosks, tea stalls & quick bites", popular=True),
    PlaceCategory(id="cafe", label="Cafes", icon="coffee", group="sustenance", description="Filter coffee, bakeries & air-conditioned seating"),
    PlaceCategory(id="parking", label="Parking", icon="square-parking", group="mobility", description="Two-wheeler & four-wheeler commuter parking"),
    PlaceCategory(id="vehicle_repair", label="Vehicle Repair", icon="wrench", group="mobility", description="Tyre puncture repair, mechanics & roadside assistance"),
    PlaceCategory(id="ev_charging", label="EV Charging", icon="zap", group="mobility", description="Fast DC CCS2 & AC public EV charging points", popular=True),
    PlaceCategory(id="police", label="Police Stations", icon="shield", group="emergency", description="Local law enforcement & highway patrol outposts", is_emergency=True),
    PlaceCategory(id="fire_station", label="Fire Stations", icon="flame", group="emergency", description="Municipal fire rescue & disaster management", is_emergency=True),
    PlaceCategory(id="hotel", label="Hotels", icon="bed", group="civic", description="Transit lodging, rooms & overnight stay facilities"),
    PlaceCategory(id="bus_stop", label="Bus Stops", icon="bus", group="mobility", description="Town bus stages, express highway shelters & depots", popular=True),
    PlaceCategory(id="railway_station", label="Railway Stations", icon="train", group="mobility", description="Southern Railway junctions & suburban halts", popular=True),
    PlaceCategory(id="taxi_stand", label="Taxi / Auto Stands", icon="car", group="mobility", description="Prepaid autorickshaw & shared cab pick-up stands", popular=True),
]

# Rich dataset centered around Tirunelveli-Tuticorin (Vagaikulam Airport to FXEC Campus corridor) and Coimbatore demo hub
DEMO_PLACES_LIST: List[PlaceItem] = [
    # --- Vagaikulam / Airport Area (Near Origin) ---
    PlaceItem(
        id="plc-vag-pharm-01",
        name="Apollo Pharmacy — Vagaikulam NH Junction",
        category="pharmacy",
        category_label="Pharmacies / Medicine",
        category_group="medical",
        icon="pill",
        lat=8.7262,
        lng=77.9862,
        address="NH 138 Airport Access Road, Vagaikulam, Thoothukudi",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Daily",
        phone="+91 462 258 4401",
        website="https://www.apollopharmacy.in",
        rating=4.6,
        reviews_count=184,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="bus_stop",
        corridor_segment="Vagaikulam Feeder Stop",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=False, summary="Ground level with wide double doors"),
        risk_zone_warning=None
    ),
    PlaceItem(
        id="plc-vag-pharm-02",
        name="MedPlus Chemist & Essentials",
        category="pharmacy",
        category_label="Pharmacies / Medicine",
        category_group="medical",
        icon="pill",
        lat=8.7271,
        lng=77.9835,
        address="Opposite Vagaikulam Post Office, Tuticorin Main Road",
        status="Open Now",
        is_open=True,
        opening_hours="07:30 AM - 11:00 PM",
        phone="+91 462 258 9112",
        rating=4.4,
        reviews_count=92,
        source="demo_simulation",
        verification_status="DEMO",
        context_anchor="bus_stop",
        corridor_segment="Vagaikulam Feeder Stop",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=False, summary="Ramped sidewalk access"),
        risk_zone_warning="Shortest path crosses unpaved shoulder near NH 138"
    ),
    PlaceItem(
        id="plc-vag-rest-01",
        name="Hotel Saravana Bhavan Highway Eatery",
        category="restaurant",
        category_label="Restaurants",
        category_group="sustenance",
        icon="utensils",
        lat=8.7255,
        lng=77.9875,
        address="Near Vagaikulam Feeder Stop, Thoothukudi-Tirunelveli Highway",
        status="Open Now",
        is_open=True,
        opening_hours="06:00 AM - 10:30 PM",
        phone="+91 462 258 3390",
        rating=4.3,
        reviews_count=412,
        source="demo_simulation",
        verification_status="DEMO",
        context_anchor="bus_stop",
        corridor_segment="Vagaikulam Feeder Stop",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Spacious ground-floor dining with accessible washroom")
    ),
    PlaceItem(
        id="plc-vag-rest-02",
        name="Udupi Sri Krishna Tiffin Center",
        category="restaurant",
        category_label="Restaurants",
        category_group="sustenance",
        icon="utensils",
        lat=8.7248,
        lng=77.9840,
        address="Panchayat Union Office Road, Vagaikulam",
        status="Open Now",
        is_open=True,
        opening_hours="06:30 AM - 09:30 PM",
        phone="+91 462 258 1144",
        rating=4.1,
        reviews_count=138,
        source="demo_simulation",
        verification_status="DEMO",
        context_anchor="bus_stop",
        corridor_segment="Vagaikulam Feeder Stop",
        accessibility=AccessibilityInfo(step_free_entrance=False, wheelchair_ramp=False, accessible_restroom=False, summary="Two exterior stone steps")
    ),
    PlaceItem(
        id="plc-vag-toilet-01",
        name="TNSTC Municipal Sanitation Facility",
        category="toilet",
        category_label="Public Toilets",
        category_group="civic",
        icon="bath",
        lat=8.7259,
        lng=77.9852,
        address="Vagaikulam Highway Bus Bay Platform, NH 138",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Daily",
        rating=3.9,
        reviews_count=65,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="bus_stop",
        corridor_segment="Vagaikulam Feeder Stop",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Wheelchair stall with support handrails")
    ),
    PlaceItem(
        id="plc-vag-atm-01",
        name="State Bank of India (SBI) 24/7 ATM",
        category="atm",
        category_label="ATMs",
        category_group="financial",
        icon="credit-card",
        lat=8.7265,
        lng=77.9845,
        address="NH 138 Junction Commercial Complex, Vagaikulam",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 ATM",
        rating=4.2,
        reviews_count=78,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="bus_stop",
        corridor_segment="Vagaikulam Feeder Stop",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=False, summary="Audio tactile keypad & ramped threshold")
    ),
    PlaceItem(
        id="plc-vag-fuel-01",
        name="Indian Oil Petrol Bunk & Clean Restroom",
        category="fuel",
        category_label="Petrol / Fuel",
        category_group="mobility",
        icon="fuel",
        lat=8.7278,
        lng=77.9890,
        address="NH 138 Mile 12, Vagaikulam Bypass",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Fuel Service",
        phone="+91 462 258 7700",
        rating=4.5,
        reviews_count=260,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="corridor",
        corridor_segment="Vagaikulam Feeder Stop",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Level driveway with illuminated customer restroom")
    ),
    PlaceItem(
        id="plc-vag-ev-01",
        name="Tata Power EZ Charge DC Station",
        category="ev_charging",
        category_label="EV Charging",
        category_group="mobility",
        icon="zap",
        lat=8.7279,
        lng=77.9892,
        address="Indian Oil Bunk Forecourt, NH 138 Vagaikulam",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Automated",
        rating=4.7,
        reviews_count=88,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="corridor",
        corridor_segment="Vagaikulam Feeder Stop",
        ev_info=EVChargingInfo(connector_types=["CCS2 60kW", "Type 2 AC 22kW"], power_kw=60, total_ports=4, available_ports=3, pricing_per_kwh="₹19/kWh"),
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Drive-in barrier-free charging bay")
    ),
    PlaceItem(
        id="plc-vag-water-01",
        name="TWAD Board RO Drinking Water Kiosk",
        category="food_water",
        category_label="Food / Water",
        category_group="sustenance",
        icon="cup-soda",
        lat=8.7256,
        lng=77.9849,
        address="Vagaikulam Transit Shelter North Corner",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Automated Coin/QR Dispenser",
        rating=4.5,
        reviews_count=110,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="bus_stop",
        corridor_segment="Vagaikulam Feeder Stop",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=False, summary="Low-height accessible dispenser nozzle (90cm)")
    ),
    PlaceItem(
        id="plc-vag-cafe-01",
        name="Madras Coffee House & Bakery",
        category="cafe",
        category_label="Cafes",
        category_group="sustenance",
        icon="coffee",
        lat=8.7285,
        lng=77.9860,
        address="Airport Boulevard Road, Vagaikulam",
        status="Open Now",
        is_open=True,
        opening_hours="07:00 AM - 10:00 PM",
        rating=4.4,
        reviews_count=190,
        source="demo_simulation",
        verification_status="DEMO",
        context_anchor="bus_stop",
        corridor_segment="Vagaikulam Feeder Stop",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=False, summary="Ground floor indoor AC seating")
    ),
    PlaceItem(
        id="plc-vag-pol-01",
        name="Vagaikulam Police Outpost & Highway Patrol",
        category="police",
        category_label="Police Stations",
        category_group="emergency",
        icon="shield",
        lat=8.7268,
        lng=77.9820,
        address="NH 138 Vagaikulam Checkpoint",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Emergency Response",
        phone="112 / +91 462 258 0100",
        rating=4.1,
        reviews_count=35,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="bus_stop",
        corridor_segment="Vagaikulam Feeder Stop",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Help desk ramped access")
    ),

    # --- Thoothukudi Airport Terminal Area (Origin) ---
    PlaceItem(
        id="plc-tcr-hosp-01",
        name="Thoothukudi Airport Emergency Medical Center",
        category="hospital",
        category_label="Hospitals",
        category_group="emergency",
        icon="hospital",
        lat=8.7240,
        lng=78.0260,
        address="TCR Airport Terminal Ground Floor, Departure Gate 2",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Emergency Duty",
        phone="+91 461 227 1863",
        rating=4.8,
        reviews_count=45,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="home",
        corridor_segment="Thoothukudi Airport Terminal",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, elevator_available=True, summary="Full airport universal accessibility")
    ),
    PlaceItem(
        id="plc-tcr-taxi-01",
        name="Thoothukudi Airport Prepaid Taxi & Auto Stand",
        category="taxi_stand",
        category_label="Taxi / Auto Stands",
        category_group="mobility",
        icon="car",
        lat=8.7238,
        lng=78.0255,
        address="Airport Terminal Arrival Concourse",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Operational",
        phone="+91 461 227 1900",
        rating=4.2,
        reviews_count=310,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="home",
        corridor_segment="Thoothukudi Airport Terminal",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Wheelchair friendly pick-up kerb")
    ),

    # --- Vallanadu / Thamirabarani Highway Corridor ---
    PlaceItem(
        id="plc-val-hosp-01",
        name="Government Primary Health Centre (PHC) — Vallanadu",
        category="hospital",
        category_label="Hospitals",
        category_group="emergency",
        icon="hospital",
        lat=8.7278,
        lng=77.8825,
        address="Main Road, Vallanadu Junction, Thoothukudi Dist",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Casualty & Maternal Care",
        phone="+91 462 253 2210",
        rating=4.2,
        reviews_count=98,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="corridor",
        corridor_segment="Vallanadu Highway Junction",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Stretcher and wheelchair ramp available")
    ),
    PlaceItem(
        id="plc-val-repair-01",
        name="Selvam Auto & Heavy Vehicle Workshop (24h Puncture)",
        category="vehicle_repair",
        category_label="Vehicle Repair",
        category_group="mobility",
        icon="wrench",
        lat=8.7282,
        lng=77.8810,
        address="Vallanadu Toll Plaza Link, NH 138",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Emergency Repairs",
        phone="+91 94431 88204",
        rating=4.6,
        reviews_count=145,
        source="demo_simulation",
        verification_status="DEMO",
        context_anchor="corridor",
        corridor_segment="Vallanadu Highway Junction",
        accessibility=AccessibilityInfo(step_free_entrance=True, summary="Roadside open garage access")
    ),
    PlaceItem(
        id="plc-val-hotel-01",
        name="Hotel Highway Grand Residency",
        category="hotel",
        category_label="Hotels",
        category_group="civic",
        icon="bed",
        lat=8.7269,
        lng=77.8840,
        address="Vallanadu Deer Sanctuary Highway Road",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Front Desk",
        phone="+91 462 253 4488",
        rating=4.1,
        reviews_count=210,
        source="demo_simulation",
        verification_status="DEMO",
        context_anchor="corridor",
    ),
    PlaceItem(
        id="plc-val-fuel-01",
        name="HPCL Highway Toll Petrol Bunk & ATM",
        category="fuel",
        category_label="Petrol / Fuel",
        category_group="mobility",
        icon="fuel",
        lat=8.7272,
        lng=77.8830,
        address="NH 138 Km 22, Near Vallanadu Toll Plaza",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Service",
        rating=4.3,
        reviews_count=175,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="corridor",
        corridor_segment="Vallanadu Highway Junction",
        accessibility=AccessibilityInfo(step_free_entrance=True, summary="Driveway level access")
    ),
    PlaceItem(
        id="plc-val-water-01",
        name="Vallanadu Highway Aavin Milk & Tea Parlour",
        category="food_water",
        category_label="Food / Water",
        category_group="sustenance",
        icon="cup-soda",
        lat=8.7280,
        lng=77.8818,
        address="Opposite Vallanadu Bus Shelter, NH 138",
        status="Open Now",
        is_open=True,
        opening_hours="05:30 AM - 10:30 PM",
        rating=4.5,
        reviews_count=320,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="corridor",
        corridor_segment="Vallanadu Highway Junction",
        accessibility=AccessibilityInfo(step_free_entrance=True, summary="Paved forecourt")
    ),

    # --- Thamirabarani River Bridge Corridor (Midway between Vallanadu and Tirunelveli) ---
    PlaceItem(
        id="plc-thm-cafe-01",
        name="Thamirabarani River View Cafe & Restroom",
        category="cafe",
        category_label="Cafes",
        category_group="sustenance",
        icon="coffee",
        lat=8.7292,
        lng=77.7855,
        address="Thamirabarani River Bridge East Approach, NH 138",
        status="Open Now",
        is_open=True,
        opening_hours="06:00 AM - 11:00 PM",
        phone="+91 462 254 8810",
        rating=4.6,
        reviews_count=490,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="corridor",
        corridor_segment="Thamirabarani River Bridge",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Ramped scenic dining deck with accessible restrooms")
    ),
    PlaceItem(
        id="plc-thm-pharm-01",
        name="Alwarkurichi Jan Aushadhi Generic Chemist",
        category="pharmacy",
        category_label="Pharmacies / Medicine",
        category_group="medical",
        icon="pill",
        lat=8.7285,
        lng=77.7840,
        address="River Bridge Service Road, Thoothukudi-Tirunelveli Link",
        status="Open Now",
        is_open=True,
        opening_hours="08:00 AM - 10:00 PM",
        phone="+91 462 254 1109",
        rating=4.4,
        reviews_count=115,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="corridor",
        corridor_segment="Thamirabarani River Bridge",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, summary="Step-free roadside access")
    ),
    PlaceItem(
        id="plc-thm-toilet-01",
        name="Highways Department Clean Public Restroom",
        category="toilet",
        category_label="Public Toilets",
        category_group="civic",
        icon="bath",
        lat=8.7289,
        lng=77.7860,
        address="NH 138 Rest Area, Thamirabarani East Bank",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Maintained",
        rating=4.1,
        reviews_count=85,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="corridor",
        corridor_segment="Thamirabarani River Bridge",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Wheelchair accessible toilet cubicle")
    ),
    PlaceItem(
        id="plc-thm-fuel-01",
        name="Bharat Petroleum (BPCL) Bridge Service Station",
        category="fuel",
        category_label="Petrol / Fuel",
        category_group="mobility",
        icon="fuel",
        lat=8.7298,
        lng=77.7870,
        address="NH 138 Mile 28, Thamirabarani Bridge Forecourt",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Fuel & Air",
        phone="+91 462 254 0090",
        rating=4.5,
        reviews_count=210,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="corridor",
        corridor_segment="Thamirabarani River Bridge",
        accessibility=AccessibilityInfo(step_free_entrance=True, summary="Level forecourt with air/nitrogen bay")
    ),

    # --- Tirunelveli Junction Intermodal Hub ---
    PlaceItem(
        id="plc-jn-pharm-01",
        name="Jan Aushadhi Medical Store — Station Road",
        category="pharmacy",
        category_label="Pharmacies / Medicine",
        category_group="medical",
        icon="pill",
        lat=8.7284,
        lng=77.7188,
        address="Platform 1 Exit, Tirunelveli Junction Railway Station",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Daily",
        phone="+91 462 233 4488",
        rating=4.5,
        reviews_count=340,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="station",
        corridor_segment="Tirunelveli Junction",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, summary="Direct concourse level access")
    ),
    PlaceItem(
        id="plc-jn-rest-01",
        name="Aryas Heritage Pure Veg Restaurant — Junction",
        category="restaurant",
        category_label="Restaurants",
        category_group="sustenance",
        icon="utensils",
        lat=8.7282,
        lng=77.7192,
        address="Opposite Railway Station Arch, Tirunelveli Junction",
        status="Open Now",
        is_open=True,
        opening_hours="06:00 AM - 11:00 PM",
        phone="+91 462 233 9900",
        rating=4.6,
        reviews_count=1240,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="station",
        corridor_segment="Tirunelveli Junction",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Ramped entrance with accessible dining booths")
    ),
    PlaceItem(
        id="plc-jn-atm-01",
        name="Canara Bank & Axis Bank 24/7 ATM Concourse",
        category="atm",
        category_label="ATMs",
        category_group="financial",
        icon="credit-card",
        lat=8.7279,
        lng=77.7182,
        address="Railway Concourse East Gate, Tirunelveli Junction",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 ATM",
        rating=4.3,
        reviews_count=190,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="station",
        corridor_segment="Tirunelveli Junction",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, summary="Braille keypad & voice guidance")
    ),
    PlaceItem(
        id="plc-jn-taxi-01",
        name="Tirunelveli Junction Prepaid Auto & Taxi Stand",
        category="taxi_stand",
        category_label="Taxi / Auto Stands",
        category_group="mobility",
        icon="car",
        lat=8.7277,
        lng=77.7175,
        address="Main Station Forecourt, Tirunelveli Junction",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Operational",
        phone="+91 462 233 1111",
        rating=4.2,
        reviews_count=850,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="station",
        corridor_segment="Tirunelveli Junction",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, summary="Dedicated accessible taxi bay")
    ),

    # --- Vannarpettai / FXEC Campus Area (Near Destination) ---
    PlaceItem(
        id="plc-van-hosp-01",
        name="Galaxy Hospital Multispeciality",
        category="hospital",
        category_label="Hospitals",
        category_group="emergency",
        icon="hospital",
        lat=8.7312,
        lng=77.7145,
        address="104 South Bypass Road, Vannarpettai, Tirunelveli - 627003",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Emergency & ICU",
        phone="+91 462 250 1800",
        website="https://www.galaxyhospitals.in",
        rating=4.7,
        reviews_count=520,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="destination",
        corridor_segment="Vannarpettai Bypass (FXEC Gate)",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, elevator_available=True, summary="Accredited barrier-free facility with emergency ramps")
    ),
    PlaceItem(
        id="plc-van-hosp-02",
        name="Tirunelveli Medical College Hospital (TVMCH)",
        category="hospital",
        category_label="Hospitals",
        category_group="emergency",
        icon="hospital",
        lat=8.7180,
        lng=77.7420,
        address="High Ground, Palayamkottai, Tirunelveli - 627011",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Tertiary Trauma Care",
        phone="108 / +91 462 257 2733",
        rating=4.5,
        reviews_count=1890,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="destination",
        corridor_segment="Palayamkottai / TVMCH",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, elevator_available=True, summary="Government tertiary hospital with tactile corridors")
    ),
    PlaceItem(
        id="plc-van-pharm-01",
        name="Vasantha Medicals & Surgical Store",
        category="pharmacy",
        category_label="Pharmacies / Medicine",
        category_group="medical",
        icon="pill",
        lat=8.7295,
        lng=77.7132,
        address="12 FXEC College Road, Vannarpettai, Tirunelveli",
        status="Open Now",
        is_open=True,
        opening_hours="08:00 AM - 11:00 PM",
        phone="+91 462 250 0914",
        rating=4.5,
        reviews_count=145,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="destination",
        corridor_segment="Vannarpettai Bypass (FXEC Gate)",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, summary="Step-free storefront facing FXEC north gate")
    ),
    PlaceItem(
        id="plc-van-pharm-02",
        name="Thulasi Pharmacies India Pvt Ltd",
        category="pharmacy",
        category_label="Pharmacies / Medicine",
        category_group="medical",
        icon="pill",
        lat=8.7288,
        lng=77.7118,
        address="North Bypass Junction, Vannarpettai, Tirunelveli",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Daily",
        phone="+91 462 250 8822",
        rating=4.6,
        reviews_count=230,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="destination",
        corridor_segment="Vannarpettai Bypass (FXEC Gate)",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=False, summary="Ground floor level entrance")
    ),
    PlaceItem(
        id="plc-van-rest-01",
        name="FX Canteen & Student Food Court",
        category="restaurant",
        category_label="Restaurants",
        category_group="sustenance",
        icon="utensils",
        lat=8.7305,
        lng=77.7120,
        address="Inside Francis Xavier Engineering College Campus, Gate 1",
        status="Open Now",
        is_open=True,
        opening_hours="07:30 AM - 07:00 PM",
        rating=4.6,
        reviews_count=380,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="destination",
        corridor_segment="Vannarpettai Bypass (FXEC Gate)",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Campus universal access compliant")
    ),
    PlaceItem(
        id="plc-van-rest-02",
        name="Anjappar Chettinad Restaurant",
        category="restaurant",
        category_label="Restaurants",
        category_group="sustenance",
        icon="utensils",
        lat=8.7275,
        lng=77.7150,
        address="Vannarpettai Main Road, Opposite BSNL Bhavan",
        status="Open Now",
        is_open=True,
        opening_hours="11:00 AM - 11:00 PM",
        phone="+91 462 250 5500",
        rating=4.4,
        reviews_count=670,
        source="demo_simulation",
        verification_status="DEMO",
        context_anchor="destination",
        corridor_segment="Vannarpettai Bypass (FXEC Gate)",
        accessibility=AccessibilityInfo(step_free_entrance=True, elevator_available=True, summary="Elevator to first-floor family dining")
    ),
    PlaceItem(
        id="plc-van-bank-01",
        name="Canara Bank & Foreign Exchange",
        category="bank",
        category_label="Banks",
        category_group="financial",
        icon="landmark",
        lat=8.7291,
        lng=77.7140,
        address="Vannarpettai Bypass, Tirunelveli",
        status="Open Now",
        is_open=True,
        opening_hours="10:00 AM - 04:00 PM",
        phone="+91 462 250 1122",
        rating=4.0,
        reviews_count=75,
        source="demo_simulation",
        verification_status="DEMO",
        context_anchor="destination",
        corridor_segment="Vannarpettai Bypass (FXEC Gate)",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, summary="Banking hall equipped with low-height counter")
    ),
    PlaceItem(
        id="plc-van-grocery-01",
        name="Reliance Smart Point Supermarket",
        category="grocery",
        category_label="Grocery Stores",
        category_group="sustenance",
        icon="shopping-cart",
        lat=8.7282,
        lng=77.7160,
        address="Bypass Road, Vannarpettai, Tirunelveli",
        status="Open Now",
        is_open=True,
        opening_hours="07:00 AM - 10:00 PM",
        rating=4.3,
        reviews_count=410,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="destination",
        corridor_segment="Vannarpettai Bypass (FXEC Gate)",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, summary="Wide aisles suitable for wheelchairs and prams")
    ),
    PlaceItem(
        id="plc-van-pol-01",
        name="Vannarpettai Law & Order Police Station",
        category="police",
        category_label="Police Stations",
        category_group="emergency",
        icon="shield",
        lat=8.7265,
        lng=77.7168,
        address="Vannarpettai Circle, Tirunelveli",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Duty",
        phone="100 / +91 462 250 0100",
        rating=4.0,
        reviews_count=42,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="destination",
        corridor_segment="Vannarpettai Bypass (FXEC Gate)",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, summary="Ramp to reception desk")
    ),
    PlaceItem(
        id="plc-van-fire-01",
        name="Tirunelveli Central Fire & Rescue Station",
        category="fire_station",
        category_label="Fire Stations",
        category_group="emergency",
        icon="flame",
        lat=8.7220,
        lng=77.7190,
        address="Junction Road, Near Sripuram, Tirunelveli",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Emergency Dispatch",
        phone="101 / +91 462 233 4401",
        rating=4.7,
        reviews_count=65,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="destination",
        corridor_segment="Tirunelveli Junction",
        accessibility=AccessibilityInfo(step_free_entrance=True, summary="Direct ground driveway")
    ),
    PlaceItem(
        id="plc-van-park-01",
        name="Vannarpettai Smart Multi-Level Vehicle Parking",
        category="parking",
        category_label="Parking",
        category_group="mobility",
        icon="square-parking",
        lat=8.7298,
        lng=77.7112,
        address="Opposite FXEC North Arch, Vannarpettai",
        status="Open Now",
        is_open=True,
        opening_hours="06:00 AM - 11:00 PM",
        rating=4.4,
        reviews_count=130,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="destination",
        corridor_segment="Vannarpettai Bypass (FXEC Gate)",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, elevator_available=True, summary="Designated accessible bays near exit lifts")
    ),

    # --- Tirunelveli Junction & New Bus Stand (Intermodal Hubs) ---
    PlaceItem(
        id="plc-jn-rail-01",
        name="Tirunelveli Junction Railway Station (TEN)",
        category="railway_station",
        category_label="Railway Stations",
        category_group="mobility",
        icon="train",
        lat=8.7280,
        lng=77.7180,
        address="Station Road, Tirunelveli Town - 627001",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Rail Operations",
        phone="+91 462 233 1336",
        website="https://www.irctc.co.in",
        rating=4.5,
        reviews_count=2400,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="station",
        corridor_segment="Tirunelveli Junction",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, elevator_available=True, tactile_paving=True, braille_signage=True, summary="Lifts to all platforms, battery carts, tactile paving")
    ),
    PlaceItem(
        id="plc-nbs-bus-01",
        name="Veppamkulam / Tirunelveli New Bus Stand (Central Terminus)",
        category="bus_stop",
        category_label="Bus Stops",
        category_group="mobility",
        icon="bus",
        lat=8.7050,
        lng=77.7280,
        address="New Bus Stand Complex, Palayamkottai, Tirunelveli",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Bus Transit",
        phone="+91 462 255 1200",
        rating=4.2,
        reviews_count=1650,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="station",
        corridor_segment="Tirunelveli New Bus Stand",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Platform ramps, sheltered waiting lounge, audio announcement")
    ),

    # --- Coimbatore Gandhipuram Central Demo Points ---
    PlaceItem(
        id="plc-gnd-pharm-01",
        name="MedPlus Gandhipuram Central",
        category="pharmacy",
        category_label="Pharmacies / Medicine",
        category_group="medical",
        icon="pill",
        lat=11.0175,
        lng=76.9692,
        address="Cross Cut Road, Gandhipuram, Coimbatore - 641012",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Daily",
        phone="+91 422 249 1102",
        rating=4.5,
        reviews_count=320,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="bus_stop",
        corridor_segment="Gandhipuram Central Terminal",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=False, summary="Ground level entrance on main shopping strip")
    ),
    PlaceItem(
        id="plc-gnd-rest-01",
        name="Sree Annapoorna Sree Gowrishankar Restaurant",
        category="restaurant",
        category_label="Restaurants",
        category_group="sustenance",
        icon="utensils",
        lat=11.0182,
        lng=76.9675,
        address="75 East Arokiasamy Road, Gandhipuram, Coimbatore",
        status="Open Now",
        is_open=True,
        opening_hours="06:00 AM - 10:30 PM",
        phone="+91 422 439 1234",
        rating=4.7,
        reviews_count=4800,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="bus_stop",
        corridor_segment="Gandhipuram Central Terminal",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, elevator_available=True, summary="Accessible seating and entrance ramps")
    ),
    PlaceItem(
        id="plc-gnd-toilet-01",
        name="Coimbatore Smart City Public E-Toilet",
        category="toilet",
        category_label="Public Toilets",
        category_group="civic",
        icon="bath",
        lat=11.0162,
        lng=76.9688,
        address="Platform 4 Outer Bay, Gandhipuram Bus Stand",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Automated",
        rating=4.0,
        reviews_count=180,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="bus_stop",
        corridor_segment="Gandhipuram Central Terminal",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, summary="Automated sensor door with ramp")
    ),
    PlaceItem(
        id="plc-gnd-atm-01",
        name="HDFC Bank ATM & Cash Deposit Machine",
        category="atm",
        category_label="ATMs",
        category_group="financial",
        icon="credit-card",
        lat=11.0170,
        lng=76.9670,
        address="Dr. Nanjappa Road, Gandhipuram, Coimbatore",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 ATM",
        rating=4.3,
        reviews_count=150,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="bus_stop",
        corridor_segment="Gandhipuram Central Terminal",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, summary="Ramped kiosk access")
    ),
    PlaceItem(
        id="plc-gnd-hosp-01",
        name="Sri Ramakrishna Hospital",
        category="hospital",
        category_label="Hospitals",
        category_group="emergency",
        icon="hospital",
        lat=11.0250,
        lng=76.9800,
        address="Sarojini Naidu Road, Sidhapudur, Coimbatore - 641044",
        status="Open 24/7",
        is_open=True,
        opening_hours="24/7 Emergency & Trauma",
        phone="108 / +91 422 450 0000",
        rating=4.6,
        reviews_count=3200,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="destination",
        corridor_segment="Gandhipuram / Sidhapudur",
        accessibility=AccessibilityInfo(step_free_entrance=True, wheelchair_ramp=True, accessible_restroom=True, elevator_available=True, summary="Tertiary emergency hospital with full accessibility")
    ),
    PlaceItem(
        id="plc-gnd-fuel-01",
        name="Bharat Petroleum (BPCL) Pure for Sure",
        category="fuel",
        category_label="Petrol / Fuel",
        category_group="mobility",
        icon="fuel",
        lat=11.0195,
        lng=76.9710,
        address="Sathy Road, Gandhipuram, Coimbatore",
        status="Open Now",
        is_open=True,
        opening_hours="24/7 Service",
        rating=4.4,
        reviews_count=390,
        source="demo_simulation",
        verification_status="LIVE_VERIFIED",
        context_anchor="corridor",
        corridor_segment="Gandhipuram Central Terminal",
        accessibility=AccessibilityInfo(step_free_entrance=True, summary="Paved forecourt")
    ),
]
